#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define PLATFORM_EMAC_BASEADDR  XPAR_LLTEMAC_0_BASEADDR
#define PLATFORM_TIMER_BASEADDR XPAR_TMRCTR_0_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_INTC_0_TMRCTR_0_VEC_ID
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << PLATFORM_TIMER_INTERRUPT_INTR)

#endif
